### ISSUE TITLE
Me gustaria modificar la tarjeta 3 para agregar mis datos

### ISSUE THREAD

**Issue by ReynagaMatias** [FlaviaBrandan/devtech-podcast-web#1]
me gustaria modifcar la tarjeta para agregar mi avatar y una descripcion la cual quedia mas o menos asi
![borrar](https://user-images.githubusercontent.com/38359386/178832087-b1f00511-8358-4ec0-98f8-6cf7ace8844b.png)
Saludos!

**Comment by FlaviaBrandan** [comment]
De acuerdo.
